source 'https://rubygems.org'
gem 'sinatra'
gem 'pg'
gem 'rake'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.18'
gem 'activerecord', '~> 4.0', '>= 4.1'
gem 'redis'
gem 'dotenv'
gem 'jwt'
gem 'pony'
gem 'puma'
gem 'rackup'
